### ISSUE TITLE
Impossible to retrieve tickets

### ISSUE THREAD

**Issue by telix** [worldline/jira2postit-front#11]
See the following error :
```
200 GET /rest/agile/1.0/board/7221/issue?fields=issuetype&fields=summary&fields=epic&fields=status&fields=components&jql=status%20IN%20(1,10093,10192,3,10007,10039,12598,10061,10013,10050)&startAt=0&maxResults=100 for user: XXXXXXX
--
  | (node:18) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'column' of undefined
  | at /usr/src/app/app/controllers/jiraController.js:259:98
  | at Array.filter (<anonymous>)
  | at /usr/src/app/app/controllers/jiraController.js:259:65
  | at Array.map (<anonymous>)
  | at /usr/src/app/app/controllers/jiraController.js:256:60
  | at processTicksAndRejections (internal/process/task_queues.js:93:5)
  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by telix** [comment]
Bad project (re-open on jira2postit-back)
